//
// Created by Administrator on 2023/8/19.
//

#ifndef DSA_ERRORCONSTANT_H
#define DSA_ERRORCONSTANT_H

#define INDEX_OUT_OF_RANGE_ERROR
#define EMPTY_ERROR
#define FULL_ERROR
#define HAS_NO_ELEMENT_ERROR
#define NULL_POINTER_EXCEPTION

#endif //DSA_ERRORCONSTANT_H
